### ISSUE TITLE
Bug in red-black tree code

### ISSUE THREAD

**Issue by danidiaz** [Abhiroop/okasaki#1]
Hi,

There seems to be a bug in the code for the red-black-tree. For example, this causes an exception:

> delete "foo" (insert "foo" (insert "bar" E))
> *** Exception: Main.hs:(84,1)-(87,59): Non-exhaustive patterns in function balR

**Comment by Abhiroop** [comment]
Thanks for reporting. https://github.com/Abhiroop/okasaki/commit/292601deb36ea57e080524275dd1c090de15e27f should fix this.

It was extremely hard to track and fix this minute bug. Took me a couple of hours. If people actually intend to use this, I should add Quickcheck tests for it. Also I should add that this implementation is actually a `Set` rather than a `Tree`.  I basically added a delete functionality to the Red Black Tree backed Set demonstrated in Okasaki.

**Comment by danidiaz** [comment]
I'm not using the code as-is, but i'm using it as an inspiration and that bug cropped up. Thanks for the fix!

**Comment by Abhiroop** [comment]
Closing this as https://github.com/Abhiroop/okasaki/commit/292601deb36ea57e080524275dd1c090de15e27f fixes this.
